FROM gracenoah/stellar-core:v12.4.0

LABEL maintainer="hello@satoshipay.io"

ADD install.gcloud.sh /
RUN /install.gcloud.sh

ADD entry.gcloud.sh /
ENTRYPOINT ["/entry.gcloud.sh"]

CMD ["/usr/local/bin/stellar-core", "run", "--conf", "/tmp/stellar-core.cfg"]
